---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: announcer-orchestrator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cloudnative-id/kubeops.git
    targetRevision: HEAD
    path: announcer-system
    helm:
      valueFiles:
      - orchestrator-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: announcer-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: announcer-kubeweekly-content
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cloudnative-id/kubeops.git
    targetRevision: HEAD
    path: announcer-system
    helm:
      valueFiles:
      - kubeweekly-content-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: announcer-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/helm/charts
    path: stable/nginx-ingress
    helm:
      releaseName: nginx-ingress
      parameters:
      - name: rbac.create
        value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/helm/charts
    path: stable/sealed-secrets
    helm:
      releaseName: sealed-secrets
      parameters:
      - name: image.repository
        value: quay.io/bitnami/sealed-secrets-controller
      - name: image.tag
        value: v0.9.6
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
