---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeweekly
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cloudnative-id/kubeops.git
    targetRevision: HEAD
    path: kubeweekly
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeweekly 