---
apiVersion: v1
name: Announcer System
version: 0.1.0
# kubeVersion: A SemVer range of compatible Kubernetes versions (optional)
description: Announcer System for Cloud Native Indonesia 
keywords:
  - announcersystem
home: https://github.com/cloudnative-id/announcer-system
engine: gotpl # The name of the template engine (optional, defaults to gotpl)
#icon: A URL to an SVG or PNG image to be used as an icon (optional).
#appVersion: The version of the app that this contains (optional). This needn't be SemVer.
#deprecated: Whether this chart is deprecated (optional, boolean)
#tillerVersion: The version of Tiller that this chart requires. This should be expressed as a SemVer range: ">2.0.0" (optional)
