# define how many completed pod jobs
jobHistoryLimit: 1

# cronjob
cronjob:
  name: announcer-cncf-webinar-content-cronjob
  image:
    name: "announcer-cncf-webinar-content"
    repository: "cloudnativeid/announcer-cncf-webinar-content"
    tag: "1.0.0"
  cronSchedule: "0 0 * * *"
  
  extraArgs: []

  envFromSecrets:
  - name: USERNAME
    valueFrom:
      secretKeyRef:
        name: github-user-secret
        key: github-user
  - name: PASSWORD
    valueFrom:
      secretKeyRef:
        name: github-token-secret
        key: github-token


