# define how many completed pod jobs
jobHistoryLimit: 1

# cronjob
cronjob:
  name: announcer-orchestrator-cronjob
  image:
    name: "announcer-orchestrator"
    repository: "cloudnativeid/announcer-orchestrator"
    tag: "1.0.0"
  cronSchedule: "10 6,7,8,9,10,11,12,18 * * *"

  extraArgs: []

  envFromSecrets:
  - name: TELEGRAM_CHATID
    valueFrom:
      secretKeyRef:
        name: telegram-chatid-secret
        key: telegram-chatid
  - name: TELEGRAM_TOKEN
    valueFrom:
      secretKeyRef:
        name: telegram-token-secret
        key: telegram-token
  - name: USERNAME
    valueFrom:
      secretKeyRef:
        name: github-user-secret
        key: github-user
  - name: PASSWORD
    valueFrom:
      secretKeyRef:
        name: github-token-secret
        key: github-token
