---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
spec:
  successfulJobsHistoryLimit: {{ .Values.jobHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.jobHistoryLimit }}
  schedule: {{ .Values.cronjob.cronSchedule }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: {{ .Values.cronjob.image.name }}
            image: "{{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag }}"
            {{- if .Values.cronjob.extraArgs }}
            args:
{{ toYaml .Values.cronjob.extraArgs | indent 12 }}
            {{- end }}
            {{- if .Values.cronjob.envFromSecrets }}
            env:
{{ toYaml .Values.cronjob.envFromSecrets | indent 12 }}
            {{- end }}