# define how many completed pod jobs
jobHistoryLimit: 1

# scraper cronjob
scrapper:
  image:
    name: "kubeweekly-scrapper-job"
    repository: "cloudnativeid/kubeweekly"
    tag: "1.0.0"
  cronSchedule: "0 6,7,8,9,10,11,12,18 * * *"
  
  extraArgs:
  - npm run trigger

  envFromSecrets:
  - name: USER
    value: 'cncfidbot'
  - name: PASS
    valueFrom:
      secretKeyRef:
        name: github-token-secret
        key: github-token

telegramBot:
  image:
    name: "kubeweekly-telegrambot-job"
    repository: "cloudnativeid/kubeweekly_telegram_bot"
    tag: "1.0.1"
  cronSchedule: "10 6,7,8,9,10,11,12,18 * * *"

  extraArgs: []

  envFromSecrets:
  - name: CHATID
    valueFrom:
      secretKeyRef:
        name: telegram-chatid-secret
        key: telegram-chatid
  - name: TELEGRAM_TOKEN
    valueFrom:
      secretKeyRef:
        name: telegram-token-secret
        key: telegram-token
  - name: GITHUB_TOKEN
    valueFrom:
      secretKeyRef:
        name: github-token-secret
        key: github-token