apiVersion: community.io/v1alpha1
kind: Announcement
metadata:
  name: oicndi-2020-announcement-01
spec:
  title: "Open Infrastructure & Cloud Native Day Indonesia 2020"
  community: Cloud Native Indonesia Community 
  message: >-
    Pendaftaran Open Infrastructure & Cloud Native Day Indonesia 2020 telah resmi dibuka! Acara kolaborasi antara OpenStack Indonesia, Cloud Native Indonesia, Open Networking Indonesia, Gimpscape-ID dan berbagai mitra komunitas yang aktif bergabung. Yuk segera daftar dan jadilah bagian dari konferensi keren ini!!😄


    Info lebih lanjut: https://s.id/oi_cnd2020info
 
    Link pendaftaran: https://s.id/oicndi20-reg
  image: https://www.openstack.id/wp-content/uploads/2020/10/register-oicndi20-12102020.jpg
  tags:
    - announcement
    - event
    - oicndi
